export {
  RobotRock,
  RobotRockError,
  attachWebhookToActions,
  createClient,
  type RobotRockAdvancedConfig,
  type RobotRockConfig,
  type RobotRockWebhookClientConfig,
  type RobotRockPollingClientConfig,
  type RobotRockWebhookConfig,
  type RobotRockPollingOptions,
  type SendToHumanInput,
  type SendToHumanActionInput,
  type SendToHumanValidUntil,
  type SendToHumanResult,
  type SendUpdateInput,
  type TasksApi,
  type ListTasksInput,
  type SearchTasksInput,
} from "./client.js";
export {
  createChatsApi,
  type ChatsApi,
  type CreateChatInput,
  type CreateChatResult,
  type CreatedChat,
  type CloseChatOptions,
  type StageChatHitlRequestsInput,
  type StagedChatHitlRequest,
} from "./chats.js";
export {
  createAgentChatBodySchema,
  agentChatSeedMessageSchema,
  type AgentChatSeedMessage,
  type CreateAgentChatBody,
  type CreateAgentChatBodyInput,
} from "@robotrock/core";
export { resolveRobotRockConfig, resolveRobotRockClient } from "./env.js";
export {
  TaskTimeoutError,
  TaskExpiredError,
  toDiscriminatedApprovalResult,
} from "./approval-result.js";
export {
  PLATFORM_MARK_DONE_ACTION_ID,
  PLATFORM_MARK_DONE_ACTION_TITLE,
  PLATFORM_REJECT_REQUEST_ACTION_ID,
  PLATFORM_REJECT_REQUEST_ACTION_TITLE,
  PLATFORM_TERMINAL_ACTION_IDS,
  PlatformRejectRequestError,
  assertNotPlatformRejectRequest,
  isPlatformMarkDoneAction,
  isPlatformRejectRequestAction,
  isPlatformTerminalAction,
  parseHandledOutcome,
  parsePlatformRejectRequestData,
  shouldStopAgentForHandledAction,
  type HandledActionInput,
  type HandledOutcome,
  type PlatformMarkDoneOutcome,
  type PlatformRejectRequestData,
  type PlatformRejectRequestOutcome,
  type PlatformTerminalActionId,
  type TaskActionOutcome,
} from "./platform-actions.js";
export {
  EVE_INPUT_OTHER_CHOICE_ID,
  EVE_INPUT_OTHER_CHOICE_LABEL,
  EVE_INPUT_SUBMIT_ACTION_ID,
  DEFAULT_TOOL_DISPLAY_LABELS,
  eveInputRequestTaskType,
  eveInputRequestToActions,
  formatEveApprovalTitle,
  getToolDisplayLabel,
  normalizeEveSelectFormData,
  resolveEveInputDisplay,
  setToolDisplayLabelOverrides,
  taskHandledToEveInputResponse,
  type EveInputOption,
  type EveInputRequest,
  type EveInputRequestDisplay,
  type EveInputResponse,
  buildTaskHandledResumeMessage,
  ROBOTROCK_READY_HOOK_SLUG,
} from "./eve/index.js";
export {
  RobotRockWebhookError,
  verifyRobotRockWebhook,
  type RobotRockWebhookErrorCode,
  type RobotRockWebhookPayload,
  type VerifyRobotRockWebhookOptions,
} from "./webhook.js";
export type { RobotRockHandlerWebhookPayload } from "./handler-webhook.js";
export {
  captureRobotRockOtelHandle,
  endRobotRockHumanWaitSpan,
  recordRobotRockHandledToOtel,
  startRobotRockHumanWaitSpan,
  toRobotRockHandledOtelInput,
  type EndRobotRockHumanWaitSpanOptions,
  type RobotRockHandledOtelInput,
  type RobotRockOtelHandle,
  type RobotRockOtelRecordOptions,
} from "./record-handled-to-otel.js";
export {
  beginRobotRockHumanWaitOtel,
  finishRobotRockHumanWaitOtel,
  shouldRecordRobotRockOtel,
  stripPlatformOtelFields,
  type RobotRockCreatedTask,
  type RobotRockHumanWaitOtelSession,
  type RobotRockPlatformOtelFields,
} from "./otel-platform.js";

export {
  taskContextSchema,
  assignToSchema,
  createTaskBodySchema,
  taskPriorities,
  taskPrioritySchema,
  DEFAULT_TASK_PRIORITY,
  LOWEST_TASK_PRIORITY,
  TASK_PRIORITY_RANK,
  threadUpdateBodySchema,
  threadUpdateInputSchema,
  threadUpdateStatusSchema,
  threadUpdateStatuses,
  DEFAULT_THREAD_UPDATE_STATUS,
  TASK_CONTEXT_FORMAT_VERSION,
  agentTelemetrySchema,
  type AssignToInput,
  type AgentTelemetry,
  type AgentTelemetryInput,
  type CreateTaskBody,
  type CreateTaskBodyInput,
  type TaskContextFormatVersion,
  type ThreadUpdate,
  type ThreadUpdateBody,
  type ThreadUpdateBodyInput,
  type ThreadUpdateInput,
  type ThreadUpdateResponse,
  type ThreadUpdateSource,
  type ThreadUpdateStatus,
  type ApprovalResult,
  type DiscriminatedApprovalResult,
  type InferActionData,
  type TaskContext,
  type TaskContextInput,
  type TaskPriority,
  type TaskAction,
  type TaskResponse,
  type Task,
  type TaskStatus,
  type TaskResult,
  type TupleElementIndices,
  type Handler,
  type WebhookHandler,
  type TriggerHandler,
} from "./schemas/index.js";
